version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: "DoAn2025@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always
  
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: DoAn2025@
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
  
  redis:
    image: redis:6.2-alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass DoAn2025@
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "sa"
      RABBITMQ_DEFAULT_PASS: "DoAn2025@"
      RABBITMQ_DEFAULT_VHOST: "myHost"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: DoAn2025@
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always

volumes:
  sql_data:
  mongodb_data:
  redis_data:
  rabbitmq_data:
  postgresql_data: